name: DevOps Sessions

on:
  push:
    branches: ["testgit"]

jobs:
  Build_docker:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: package docker image
      run: |
        sudo apt update
        echo "Building DevOps class Docker Container"
        docker build . --file Dockerfile --tag Bank-App:$(date)